server:
  port: 8084
  session:
    timeout: 10
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    static-path-pattern: /**
#  resources:
#    static-locations: classpath:/static

kubernetes:
  config:
    #config-path: /root/.kube/config
    config-path: D:\\git\\config 